import { describe, expect, it } from "vitest";
import type { AlgoliaProductRecord } from "@/lib/algolia/record";
import type { StorefrontSnapshotProduct } from "@/test-support/storefront-baseline";
import { buildStorefrontSearchRecord } from "@/test-support/storefront-search-projection";

const searchableProduct = {
  id: "11111111-1111-1111-1111-111111111111",
  slug: "northpoint-renewal-serum",
  path: "/products/northpoint-renewal-serum",
  displayName: "NORTHPOINT",
  productType: "Serum",
  badge: "Night step",
  currency: "USD",
  catalogStatus: "active",
  merchandisingStatus: "available",
  editorialDescription: "A nightly serum for smoother-looking tone.",
  swatch: ["#e3ddea", "#c2b5d6"],
  sortOrder: 2,
  createdAt: "2026-06-14T00:00:00.000Z",
  publishedAt: "2026-06-14T00:00:00.000Z",
  updatedAt: "2026-06-15T00:00:00.000Z",
  madeFor: "Uneven texture or tone",
  goodFor: "Nighttime routine",
  texture: "Silky serum",
  keyIngredients: ["Niacinamide"],
  ingredients: "Water, Niacinamide",
  concerns: ["Texture"],
  usageTime: ["PM"],
  searchKeywords: ["renewal"],
  routineGroup: "core",
  systemPosition: 3,
  systemStepName: "TREAT",
  routineSort: 30,
  variants: [
    {
      id: "30ml",
      label: "30 ml",
      price: 5400,
      available: true,
      inventoryStatus: "in_stock",
      sortOrder: 0,
    },
    {
      id: "50ml",
      label: "50 ml",
      price: 7800,
      available: true,
      inventoryStatus: "low_stock",
      sortOrder: 1,
    },
  ],
  media: [
    {
      kind: "placeholder",
      url: null,
      alt: "Northpoint search surface",
      width: null,
      height: null,
      role: "search",
      sortOrder: 0,
      paletteId: "northpoint-search",
      placeholderPalette: {
        start: "#e3ddea",
        end: "#c2b5d6",
        accent: "#735f86",
      },
    },
    {
      kind: "image",
      url: "/products/northpoint/card.webp",
      alt: "Northpoint serum",
      width: 1200,
      height: 1650,
      role: "card_default",
      sortOrder: 1,
      paletteId: null,
      placeholderPalette: null,
    },
  ],
  offer: {
    variantId: "30ml",
    label: "30 ml",
    price: 5400,
    currency: "USD",
  },
} as const satisfies StorefrontSnapshotProduct;

describe("Storefront search projection", () => {
  it("maps a selected snapshot Product through the complete production Algolia contract", () => {
    const expected = {
      objectID: searchableProduct.id,
      productId: searchableProduct.id,
      slug: "northpoint-renewal-serum",
      slugAliases: [],
      displayName: "NORTHPOINT",
      editorialDescription: "A nightly serum for smoother-looking tone.",
      productType: "Serum",
      routineGroup: "core",
      systemStepPosition: 3,
      systemStepName: "TREAT",
      routineSort: 30,
      badge: "Night step",
      status: "available",
      priceMin: 5400,
      priceMax: 7800,
      currency: "USD",
      available: true,
      waitlist: false,
      variantCount: 2,
      variantNames: ["30 ml", "50 ml"],
      keywords: [
        "The Core",
        "TREAT",
        "Serum",
        "NORTHPOINT",
        "A nightly serum for smoother-looking tone.",
        "Uneven texture or tone",
        "Nighttime routine",
        "Silky serum",
        "PM",
        "Texture",
        "Niacinamide",
        "renewal",
        "30 ml",
        "50 ml",
      ],
      concerns: ["Texture"],
      ingredients: ["Niacinamide", "Water", "Niacinamide"],
      swatch: ["#e3ddea", "#c2b5d6"],
      placeholderMedia: {
        kind: "placeholder",
        alt: "Northpoint search surface",
        paletteId: "northpoint-search",
        palette: {
          start: "#e3ddea",
          end: "#c2b5d6",
          accent: "#735f86",
        },
      },
      imageMedia: {
        kind: "image",
        url: "/products/northpoint/card.webp",
        alt: "Northpoint serum",
        width: 1200,
        height: 1650,
        role: "card_default",
      },
      cardMedia: {
        kind: "gradient",
        colors: ["#e3ddea", "#c2b5d6"],
      },
      sortOrder: 30,
      createdAt: "2026-06-14T00:00:00.000Z",
      publishedAt: "2026-06-14T00:00:00.000Z",
      updatedAt: "2026-06-15T00:00:00.000Z",
      madeFor: "Uneven texture or tone",
      goodFor: "Nighttime routine",
      texture: "Silky serum",
      familyId: null,
      familySlug: null,
      familyDisplayName: null,
      familyOptionLabel: null,
      familySortOrder: null,
      familyIsEntry: null,
    } satisfies AlgoliaProductRecord;

    expect(buildStorefrontSearchRecord(searchableProduct)).toEqual(expected);
  });
});
