import "server-only";

import type { ProductEditorDocumentV4 } from "@/lib/admin/catalog/types";
import type { CoreRoutineSummary, PdpProduct } from "@/lib/catalog/models";
import type { ProductReviews } from "@/lib/catalog/product-reviews";

const productId = "00000000-0000-4000-8000-000000000354";
const timestamp = "2026-09-01T12:00:00.000Z";

// Presentation data exists only behind this route's local verification gate.
export const previewProduct: PdpProduct = {
  id: productId,
  slug: "verification-preview-product",
  displayName: "Synthetic verification product",
  routineGroup: "core",
  systemStepName: "CLEANSE",
  systemStepPosition: 1,
  routineSort: 1,
  productType: "Catalog Preview presentation",
  description: "Synthetic content for local Catalog Preview verification. This representation does not describe a product available for purchase.",
  howToUse: "Read the presentation. Inspect the expanded panels. Return to the verification editor.",
  swatch: ["#DCE8DF", "#82978A"],
  media: [{
    kind: "image",
    url: "/media/system/intentional-skincare-portrait-01.webp",
    alt: "Local editorial artwork used in synthetic profile verification",
    width: 1000,
    height: 1200,
    role: "profile_editorial",
    sortOrder: 0,
    paletteId: null,
    palette: null,
  }, {
    kind: "image",
    url: "/media/system/ingredients/panthenol.jpg",
    alt: "Local ingredient artwork used in synthetic panel verification",
    width: 800,
    height: 800,
    role: "ingredients_texture",
    sortOrder: 1,
    paletteId: null,
    palette: null,
  }],
  cardMedia: null,
  detailMedia: null,
  cartMedia: null,
  madeFor: "Local presentation verification",
  goodFor: "Inspecting panel hierarchy",
  texture: "Synthetic gel description",
  keyIngredients: ["Verification ingredient"],
  ingredients: "Synthetic ingredient list for visual verification only.",
  cautions: ["Synthetic content. Do not use as product guidance."],
  finish: "Synthetic finish description",
  volume: "100 mL",
  skinTypes: ["Synthetic skin-type label"],
  usageTime: ["Morning", "Night"],
  pdpContent: {
    schemaVersion: 1,
    profileTitleTokens: [{ text: "Synthetic profile" }],
    routineOverlay: "Synthetic routine context",
    outcomeHeading: "Presentation outcomes",
    outcomeLabels: ["First", "Second", "Third"],
    howToUseSteps: ["Read the presentation", "Inspect the expanded panels", "Return to the verification editor"],
    applicationSteps: ["First synthetic step", "Second synthetic step", "Third synthetic step"],
    ingredientCards: [{
      name: "Verification ingredient",
      label: "Presentation",
      copy: "Synthetic explanatory copy exercises the gray education panel.",
    }],
    ingredientStory: {
      heading: "Synthetic ingredient story",
      intro: "Local presentation content for checking nested panels and wrapping.",
      highlights: [
        { name: "First synthetic ingredient", description: "First presentation description." },
        { name: "Second synthetic ingredient", description: "Second presentation description." },
      ],
      supportingIngredients: "Synthetic supporting ingredients",
    },
    routineGuidance: "Synthetic routine guidance for local verification only.",
  },
  productFamily: null,
  currency: "USD",
  status: "available",
  variants: [{
    id: "00000000-0000-4000-8000-000000000355",
    productId,
    productSlug: "verification-preview-product",
    productStatus: "available",
    label: "100 mL",
    price: 2200,
    available: true,
    inventoryStatus: "in_stock",
    volume: "100 mL",
    packCount: 1,
    sortOrder: 0,
  }],
};

export const previewCoreProducts: CoreRoutineSummary[] = ([
  ["CLEANSE", 1, "cleanse"],
  ["TREAT", 3, "treat"],
  ["SEAL", 5, "seal"],
] as const).map(([name, position, stepSlug]) => ({
  id: `verification-core-${position}`,
  slug: position === 1 ? previewProduct.slug : `verification-core-${stepSlug}`,
  displayName: `Verification ${stepSlug}`,
  productType: "Synthetic routine presentation",
  description: "Synthetic Core routine content for local visual verification.",
  benefits: ["Synthetic benefit"],
  goodFor: "Presentation verification",
  texture: "Synthetic texture",
  finish: "Synthetic finish",
  keyIngredients: ["Verification ingredient"],
  routineGroup: "core",
  systemStepName: name,
  systemStepPosition: position,
  routineSort: position,
  swatch: ["#DCE8DF", "#82978A"],
  textureMedia: {
    kind: "image",
    url: "/media/home/cleanse-product-card-default-01.webp",
    alt: "Local cleanser artwork reused for synthetic routine verification",
    width: 1200,
    height: 1650,
    role: "core_routine_texture",
    sortOrder: 0,
    paletteId: null,
    palette: null,
  },
  editorialMedia: null,
  cardMedia: null,
  cartMedia: null,
  pdpContent: previewProduct.pdpContent,
  status: "available",
  variants: [],
}));

export const previewDocument: ProductEditorDocumentV4 = {
  schemaVersion: 4,
  productId,
  product: {
    id: productId,
    slug: previewProduct.slug,
    display_name: previewProduct.displayName,
    product_type: previewProduct.productType,
    editorial_description: previewProduct.description,
    editorial_how_to_use: previewProduct.howToUse,
    badge: "Synthetic verification",
    benefits: ["Inspecting the neutral surface hierarchy", "Checking long metadata wrapping on mobile"],
    catalog_status: "active",
    status: "available",
    currency: "USD",
    routine_group: "core",
    system_step_name: "CLEANSE",
    routine_sort: 1,
    sort_order: 1,
    swatch_from: previewProduct.swatch[0],
    swatch_to: previewProduct.swatch[1],
    cautions: previewProduct.cautions,
    concerns: ["Synthetic concern"],
    finish: previewProduct.finish,
    formula_notes: ["Synthetic formula note"],
    good_for: previewProduct.goodFor,
    ingredients: previewProduct.ingredients,
    key_ingredients: previewProduct.keyIngredients,
    made_for: previewProduct.madeFor,
    search_keywords: ["synthetic", "presentation", "local verification"],
    seo_title: "Synthetic verification product | helix",
    seo_description: "Synthetic metadata for local visual verification; no catalog records or provider data are loaded by this fixture.",
    skin_types: previewProduct.skinTypes,
    texture: previewProduct.texture,
    usage_time: previewProduct.usageTime,
    volume: previewProduct.volume,
    created_at: timestamp,
    updated_at: timestamp,
    published_at: timestamp,
  },
  productPdpContent: {
    product_id: productId,
    schema_version: 1,
    profile_title_tokens: previewProduct.pdpContent!.profileTitleTokens,
    routine_overlay: previewProduct.pdpContent!.routineOverlay,
    outcome_heading: previewProduct.pdpContent!.outcomeHeading,
    outcome_labels: previewProduct.pdpContent!.outcomeLabels,
    how_to_use_steps: previewProduct.pdpContent!.howToUseSteps,
    application_steps: previewProduct.pdpContent!.applicationSteps,
    ingredient_cards: previewProduct.pdpContent!.ingredientCards,
    ingredient_story: previewProduct.pdpContent!.ingredientStory,
    routine_guidance: previewProduct.pdpContent!.routineGuidance,
    created_at: timestamp,
    updated_at: timestamp,
  },
  variants: [{
    id: previewProduct.variants[0].id,
    product_id: productId,
    variant_key: "verification-100ml",
    label: "100 mL",
    sku: "VERIFICATION-ONLY",
    price_cents: 2200,
    compare_at_price_cents: null,
    available: true,
    inventory_status: "in_stock",
    option_values: { size: "100 mL" },
    volume: "100 mL",
    pack_count: 1,
    sort_order: 0,
    supplier_variant_id: null,
    updated_at: timestamp,
    archived_at: null,
  }],
  media: previewProduct.media.map((media, index) => ({
    id: `00000000-0000-4000-8000-00000000036${index}`,
    product_id: productId,
    variant_id: null,
    url: media.url,
    media_type: "image",
    role: media.role,
    alt: media.alt,
    width: media.width,
    height: media.height,
    sort_order: media.sortOrder,
    palette_id: null,
    placeholder_palette: {},
    original_source_url: null,
    source_filename: null,
    created_at: timestamp,
    updated_at: timestamp,
    archived_at: null,
  })),
  relationships: [],
  productSource: null,
  productFamily: null,
};

export const previewReviews: ProductReviews = {
  meter: { question: "Synthetic review presentation", lowLabel: "Low", highLabel: "High" },
  reviews: [],
};
